services:
  adminContext:
      class:  Youshido\AdminBundle\Service\AdminContext
      arguments: [@service_container]

  admin.form.helper:
        class: Youshido\AdminBundle\Service\FormHelperService
        calls:
          - [ setContainer, [ @service_container ] ]

  adminExcelExporter:
      class: Youshido\AdminBundle\Service\ExcelExporter
      calls:
          - [setContainer, [@service_container] ]

  admin.security:
      class: Youshido\AdminBundle\Service\Security
      calls:
          - [setContainer, [@service_container] ]

  admin.twig_extension:
      class: Youshido\AdminBundle\Twig\AdminExtension
      public: true
      calls:
          - [ setContainer, [@service_container]]
      tags:
          - { name: twig.extension }


############### custom form type ############################
  admin.form.type.wysiwyg:
      class: Youshido\AdminBundle\Form\Type\WysiwygType
      tags:
          - { name: form.type, alias: wysiwyg }

  admin.form.type.html:
      class: Youshido\AdminBundle\Form\Type\HtmlType
      tags:
          - { name: form.type, alias: html }

  admin.form.type.picked_date:
      class: Youshido\AdminBundle\Form\Type\PickedDateType
      tags:
          - { name: form.type, alias: picked_date }

  admin.form.type.image:
      class: Youshido\AdminBundle\Form\Type\ImageType
      tags:
          - { name: form.type, alias: image }

  admin.form.type.date_range:
      class: Youshido\AdminBundle\Form\Type\DateRangeType
      tags:
          - { name: form.type, alias: date_range }